export const queryKeys = {
  ME: "ME",
  LOGIN_OPTIONS: "LOGIN_OPTIONS",
  ROLES: "ROLES",
  ROLE_PERMISSIONS: "ROLE_PERMISSIONS",
  USERS: "USERS",
  USER: "USER",
  EMPLOYEES: "EMPLOYEES",
  ROLE_USERS: "ROLE_USERS",
  PERMISSIONS: "PERMISSIONS",
};
